version: '3.8'

services:
  server:
    build: ./server
    container_name: waifu-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    env_file:
      - ./server/.env

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data: 